### PR TITLE
daffy duck irq non-reschedule

### PR DESCRIPTION
**Pull request by lacastri**
fix random flickering black screens

### CODE REVIEW

**Comment by lacastri** [comment]
Fixes this game but I'm not 100% sure this is hw-accurate.

**Comment by bearoso** [comment]
I don't think that would break anything. I'll have to test to find out.

**Comment by bearoso** [comment]
Seems to work fine. Would probably be more hw-accurate as well.

**Comment by Dwedit** [comment]
Just linking this to issue #418

**Pull request merged**
