### PR TITLE
BS-X Code Refactor and Cleanup

### PR DESCRIPTION
**Pull request by LuigiBlood**
I mostly want to do this pull request so we can talk about Satellaview support.

Not everything is done yet, I need to do Memory Pack loading for games like RPG Tsukuru 2 and others, and also proper Satellaview signal support, which we have to talk about since that would need to include a new folder for Satellaview specific files. I also want to do Memory Pack saving, to save custom content.

I've done it in the past with my old fork named snes9x-sx2. It did work fine before, there's no reason I wouldn't be able to implement those again.

There's one change compared to my snes9x-sx2 fork, Kirby Satellaview games are actually booting. There was an oversight where the PSRAM was mapped all over the PPU part, preventing them to do anything.

### CODE REVIEW

**Comment by OV2** [comment]
Haven't had time yet to take a look, I'll try to find some this week.

**Comment by LuigiBlood** [comment]
Just added MultiCart loading for games with Memory Pack support.
...though I noticed that LoROM games do not really support it well.

**Comment by robertybob** [comment]
@LuigiBlood Do you have any plans to add this, when tested and complete, to the Libretro emulator port? :)

**Comment by LuigiBlood** [comment]
Well technically at this point, everything should work on the libretro port just fine. I haven't touched the menus yet or added a folder for Satellaview signal files, those would require more work for Windows, Linux, Mac and Libretro.

**Comment by LuigiBlood** [comment]
I fixed Sound Novel Tsukuru's Memory Pack save support.

**Comment by LuigiBlood** [comment]
I've rewrote the BS-X stuff for the recent release of bsnes-plus so I have a better base, and now I can concentrate for snes9x code.

So I'll make a list of what I intend to do, and what's already done (for myself, and everyone):
Done:
- More accurate BS-X Memory Mapping
- Memory Pack Type 1 command emulation
- Memory Pack Multicart loading for LoROM and HiROM games

Todo:
- Memory Pack saving (pretty easy to do, could use the Save folder)
- Satellaview Signal Data (a new folder has to be made for that, also makes more games to work)
- Custom Time & Date (honestly it is pretty annoying to have the real time set to around :05 to be able to play a soundlink game)

- SA-1 Memory Pack support (I did see something but it seemed to be specialized for SD Gundam G-NEXT, and I want that to work on Itoi's Bass Fishing as well, haven't checked throughly)

**Comment by LuigiBlood** [comment]
Changed the code for SA-1 Memory Pack mapping, reported working for both SD Gundam G-NEXT and Itoi's Bass Fishing No. 1.

**Comment by LuigiBlood** [comment]
image
snes9x-sx2 didn't even do that if I remember right.

**Comment by LuigiBlood** [comment]
And I'm trying to do the Satellaview data file loading... and it doesn't load files and I don't know why D:

**Pull request merged**
