### PR TITLE
lightgun cursor grey typo

### PR DESCRIPTION
**Pull request by retrotalker**

### CODE REVIEW

**Comment by OV2** [comment]
Isn't this just AE / BE ? I don't mind either way, maybe a native speaker can give a preference.

**Comment by bearoso** [comment]
Yeah, this is personal preference. Gray is usually used in the US, grey is used in the UK, and they're both correct.

**Comment by retrotalker** [comment]
controls.cpp uses 25Grey,50Grey,75Grey so I guess we could stick with that? There's also "The Grey (2011)" movie.

**Comment by retrotalker** [comment]
Forgot to mention that this commit is for
https://github.com/snes9xgit/snes9x/issues/378

libretro GUI says Gray but strcmp(Grey) so 25,50,75 don't work atm.

**Pull request merged**
