### PR TITLE
GTK/unix fixes

### PR DESCRIPTION
**Pull request by megari**
This pull request contains fixes to make the GTK and unix frontends build and work again after the merge of the msu1-zip branch, as well as fixes to some issues detected by g++ while I was debugging the original issues.

The last patch is the least important, as the issues are minor nitpicks, but the first two fix serious issues.

### CODE REVIEW

**Comment by megari** [comment]
It seems recent changes made this pull request unmergeable. Will rebase in a jiffy.

**Comment by megari** [comment]
Rebased on current master.

**Comment by megari** [comment]
Found an additional case of undefined behavior, so added the fix for that in the appropriate commit.

**Comment by OV2** [comment]
I've left out the splitpath modifications and changed the call to pass in all parameters, since this is the only location where it was called this way. Otherwise we would have to change all _splitpath implementations: there is also mac and libretro, and possibly in other ports.

**Pull request merged**
