### PR TITLE
Unmacro tile.cpp

### PR DESCRIPTION
**Pull request by yoffy**
This patch provides maintainability and debuggability of tile.cpp.
It replacements many macros to C++ template, and abolish self inclusion.

### CODE REVIEW

**Comment by bearoso** [comment]
I was thinking about doing this before you posted it. 

I fixed the compiler error and tested it and you're getting a 3-4% total speed loss. With Snes9x, we're out of simple things to optimize, so that's a significant amount. You need to figure out what's doing that before we can commit it. I looked through the assembly, and the templating is working correctly. GetCachedTile is a vtable lookup so that might be slow.

**Comment by yoffy** [comment]
> you're getting a 3-4% total speed loss.

What OS and compiler did you test?
And, how can I measure it? (framerate, CPU cycles, benchmark test, etc.)

My environment is Raspberry Pi 3B, armv7 1.2GHz x 4core, Linux 4.19 (Raspbian 9.8), gcc 6.3.0.
It doesn't look like it's getting slower in this environment.
I also tried compiling with Visual C ++, but I got an error that 'zconf.h':No such file or directory.

**Comment by bearoso** [comment]
Linux x86_64, clang and gcc 9. LTO and non-LTO. It's slightly slower (max framerate and CPU cycles). You'd need to measure it because it's not visibly obvious. The simplest way is to just unthrottle everything on something static and see how many FPS you get.

**Comment by OV2** [comment]
On win32 x64 with my somewhat imprecise measurement (movie playback with no syncs, averaging fps) I see about 6% speed loss. SMW2 intro and turning island (PAL version), 481fps vs 452fps.

**Comment by yoffy** [comment]
We can include "snes.hpp" and define `alwaysinline` every method. Maybe it generates same code as macro implementation.
However, the size of tile.o implemented by the macro is up to 2 MB. I think too large code will cause frequent cache misses.
And I think it's better to carefully tune for slower CPUs like Raspberry Pi, than for CPUs that are already performing well.
Anyway, it may be better to use alwaysinline for this pull request and separate to tune for another pull request.

**Comment by yoffy** [comment]
I'm defined alwaysinline to functions.

**Comment by bearoso** [comment]
I'm still seeing a 1.8% speed loss with alwaysinline.

> And I think it's better to carefully tune for slower CPUs like Raspberry Pi, than for CPUs that are already performing well.

I agree. We barely managed to get a 6% increase in performance in issue #461 to help lower-end CPUs, and I'd rather not take it away so soon.

I really like this idea because it makes the code much cleaner and compiles faster, but we can't sacrifice too much performance.

This is a big change, so we won't merge until after 1.60, so there's no hurry. Get some numbers on your Raspberry Pi to see the difference. Try the Yoshi's Island 2 rotating island with an uncapped framerate like OV2. Or try the Rockman X2 areas mentioned in issue #461.

**Comment by bearoso** [comment]
It seems Clang likes these changes, and it yields a small **increase** in performance. That's pretty good. I'll have to look at the MSVC numbers, but I think performance is good enough to merge in 1.61.

**Comment by OV2** [comment]
We could also leave the macroed version in as an alternative for ports. Unless we really overhaul the whole tile file at some point it shouldn't be that much of a maintenance issue to keep them up to date.

**Comment by yoffy** [comment]
Raspberry Pi 3B and gcc 6.3.0 was also slightly slower. (40 fps-> 39 fps)
I think that caused by the compiler loading both B and C while trying to remove branches such as `A ? B : C`.
But I could not fix it.

**Comment by yoffy** [comment]
The compilation of tile on unix has been made much faster. In Raspberry Pi 3B (gcc 6.3.0) compilation of tile.cpp equivalent will be 7.8 times faster.

master branch (51edec7):
```
$ time make ../tile.o
:
real    6m17.435s
user    6m15.691s
sys     0m1.091s
```

This patch (7603ed0):
```
# parallel compilation
$ time make -j3 ../tile.o ../tileimpl-n1x1.o ../tileimpl-h2x1.o ../tileimpl-n2x1.o
:
real    0m48.442s
user    2m6.856s
sys     0m1.708s

# sequential compilation
$ time make -j1 ../tile.o ../tileimpl-n1x1.o ../tileimpl-h2x1.o ../tileimpl-n2x1.o
:
real    1m48.678s
user    1m47.046s
sys     0m1.305s
```

**Comment by bladeoner** [comment]
@ov2 @bearoso if you want I can put this in the port Snes9x GX and share it with the community to get some quick feedback. If it works fine for that port it's not necessary to maintain the macroed version for it.

I say this because the resources in the Wii are really limited. For your information it's running core 1.60 with the latest Snes9x fixes but the 1.52/1.53 APU to balance out the used resources.

Thanks in advance for your reply.

**Comment by bearoso** [comment]
Thanks. It'll be helpful to see the effect on slower hardware. I think we're probably going to change to this wholesale and try to make up any difference after.

**Comment by bladeoner** [comment]
Here are my test results for compiling Snes9x GX, without the changes:
real    23m5.593s
user    0m46.338s
sys     1m59.481s

With the changes:
real    17m55.635s
user    0m45.903s
sys     2m2.520s

So it seems we reduce some compilation time with that also.

I also tried few games myself and I barely notice a difference, so that is positive but lets wait for some more feedback on GBA Temp.

**Comment by bladeoner** [comment]
@bearoso gpt some test results back, 10 games where tested and where running more or less the same as before this change. Only one game Kirby's Dreamland 3 has some huge framedrops but that's an known issue and has nothing to do with the change.

So I would say merge the commit as it has a lot of benefits, like compilation speed but also reduction in file size of the emulator. From 5,5 MB to 5 MB for Snes9x GX.

**Pull request merged**
